version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123/?
      POSTGRES_DB: postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    # Optional: uncomment if you want Docker to wait for DB
    # depends_on:
    #   - db

volumes:
  pgdata:
