# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    network_mode: "host"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:testing@db:5433/testdb
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: testdb
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
